### ISSUE TITLE
PID information in telemetry data

### ISSUE THREAD

**Issue by netmute** [silver13/BoldClash-BWHOOP-B-03#12]
Hi silver,

we talked briefly about displaying the PID data stored in flash memory over on RCGroups.

While working on that, I had the idea to include that information into the telemetry data. I don't have the skills to do it. Would that be feasible?

It would make gesture based PID tuning a lot more convenient.

**Comment by silver13** [comment]
telemetry for devo? The problem was the display is pretty limited in what it can do, I used the spektrum template, but it has a few limitations. Overall I thought it wouldn't be quite usable enough
